In [13]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.insert(0, "../src")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [14]:
from data.FuncionesTarea import process, build_series

In [15]:
!ls ../data/raw

202512-llegadas-de-turistas-extranjeros.xlsx

In [ ]:
RAW_FILE = '../data/raw/202512-llegadas-de-turistas-extranjeros.xlsx'

df = process(RAW_FILE)

,period,region,country,crossing_type,crossing_detail,arrivals
0,2013-01-01,Europa,Alemania,Aeropuertos,Chacalluta - Aeropuerto,41
1,2013-01-01,America Del Sur,Argentina,Aeropuertos,Chacalluta - Aeropuerto,264
2,2013-01-01,Oceania,Australia,Aeropuertos,Chacalluta - Aeropuerto,77
3,2013-01-01,Europa,Austria,Aeropuertos,Chacalluta - Aeropuerto,3
4,2013-01-01,Europa,Belgica,Aeropuertos,Chacalluta - Aeropuerto,3

# Explora

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 186777 entries, 0 to 186776
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   period           186777 non-null  datetime64[us]
 1   region           186777 non-null  str
 2   country          186777 non-null  str
 3   crossing_type    186777 non-null  str
 4   crossing_detail  186777 non-null  str
 5   arrivals         186777 non-null  int64
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 8.6 MB

In [20]:
df.head()

,period,region,country,crossing_type,crossing_detail,arrivals
0,2013-01-01,Europa,Alemania,Aeropuertos,Chacalluta - Aeropuerto,41
1,2013-01-01,America Del Sur,Argentina,Aeropuertos,Chacalluta - Aeropuerto,264
2,2013-01-01,Oceania,Australia,Aeropuertos,Chacalluta - Aeropuerto,77
3,2013-01-01,Europa,Austria,Aeropuertos,Chacalluta - Aeropuerto,3
4,2013-01-01,Europa,Belgica,Aeropuertos,Chacalluta - Aeropuerto,3

# Series de tiempo

In [18]:
ts_arg = build_series(df, country="Argentina")